### ISSUE TITLE
Milestone 1: Single-Player and Multiplayer

### ISSUE THREAD

**Issue by j-richey** [fossxo/fossxo#1]
Create a working single-player and multiplayer game. This includes the Windows package, user manual, and getting the development tools in place to make the remaining milestones go faster.

**Tasks:**

* [x] Create repository
    * [x] release branch (Default). Include "Coming Soon" README. 
    * [x] develop branch
    * [x] README, CHANGELOG, LICENSE, and other typical files
* [x] `--help` and `--version` command line options
* [x] Game Board
    * [x] menu button
    * [x] status text
    * [x] next game button
* [x] Environments resources and Environment trait
* [x] Debug environment
* [x] Main Menu
    * [x] Single Player Button
    * [x] Multiplayer Button
    * [x] Help Button
    * [x] Exit Button
* [x] Single Player Menu
    * [x] Select Mark Button
    * [x] Easy / Medium / Hard / Back Buttons
* [x] Game State
* [x] Core Systems, Components, and Resources
    * [x] AI Player and Local Player systems
    * [x] Game and Grid resources
    * [x] Player, Local Player, Ai, and Mark components
* [x] Inno Installer
* [x] Minimal User Manual
    * [x] Instructions
    * [x] Software BOM
* [x] Automated license check for packages
* [x] Dependency audinting
* [x] Logging to console
* [x] Unit tests
* [x] CI support
* [x] basic cargo-make workflows
    * [x] user build
    * [x] development
    * [x] test
    * [x] package

**Anti goals:**

* Using or managing third party assets
* User configuration file (remember game settings)
* Audio support

**Comment by j-richey** [comment]
I attempted to use `cargo-about` to generate the software BOM. However, the data available to `cargo-about` is orientated towards displaying license information instead of library information. Thus the generated list is sorted by license name instead of library name.  Perhaps in milestone 2 or milestone 4 we can address this?

**Comment by j-richey** [comment]
**Useful Crates / Libraries**

I found some crates that might be helpful for completing the tasks above. 
*  [webbrowser](https://github.com/amodm/webbrowser-rs) - open links in the user's web browser. Also is a good example of setting up GitHub actions. 
* [os_info](https://github.com/stanislav-tkach/os_info) for logging the user's OS information.
* The [amethyst_window::Icon](https://docs.amethyst.rs/stable/amethyst_window/struct.Icon.html) struct can be used to configure the game's icon.

**Comment by j-richey** [comment]
Creating the `Single-player Select Mark Button` was a bit more involved than I first suspected. Therefore, I am moving it out of this milestone. Issue #6 is created to track this task.
