### ISSUE TITLE
Milestone 2: Speedrun mode

### ISSUE THREAD

**Issue by j-richey** [fossxo/fossxo#2]
Add the Speedrun mode, add audio support, and manage third party assets. The game play functionality is complete at the end of this milestone. 

**Tasks:**

* [ ] Speedrun Board 
    * [ ] Countdown to go graphics and sound FX
    * [ ] Speedrun music
    * [ ] Game timer
    * [ ] Status text / retry button / etc
* [ ] Speedrun menu
* [ ] Best time menu
* [ ] Credits Menu
    * [ ] Links to user manual
* [ ] User data file
* [ ] Asset license management
* [ ] Content complete user manual
    * [ ] Credits
    * [ ] Game Assets info
    * [ ] Key Bindings 
    * [ ] How to get support

**Anti goals:**

* screenshots in the user manual
