### ISSUE TITLE
Milestone 3: Initial Set of Environments

### ISSUE THREAD

**Issue by j-richey** [fossxo/fossxo#3]
An initial set of environments are added. The goal is to get 10 environments so a complete speedrun game can be played without a duplicate environment appearing. It is the artists and developers choose on the environments to implement.

**Tasks:**

* [ ] 10x environments
* [ ] Loading Screen
* [ ] Options Menu
* [ ] Add environment demo to Credits Menu
* [ ] Game Configuration File
* [ ] Remember last game settings
* [ ] Log to user directory
* [ ] `--debug`, `--test`, and `--environment` command line options
* [ ] Try to get some external play testing
