### ISSUE TITLE
Milestone 4: Polish and More Environments

### ISSUE THREAD

**Issue by j-richey** [fossxo/fossxo#4]
The final milestone is for adding the remaining environments, adding artwork to the installer and user manual, and creating the website.

**Tasks:**

* [ ] Update User Manual Screenshots
* [ ] Create Icons and Banners
* [ ] Add Inno Setup Art 
* [ ] Create Website
* [ ] Add environments as time allows
* [ ] Enhance existing environments as time allows
* [ ] Linux Package
